"use client";

import { useEffect, useRef, useState } from "react";
import { motion, useMotionValue, useTransform } from "framer-motion";
import { FRAME_COUNT } from "@/lib/frames.generated";
import {
  backfillIndices,
  firstPassIndices,
  frameSrc,
  planFrameLoading,
  POSTER_FRAME_INDEX,
  type FramePlan,
} from "@/lib/hero-frames";

/**
 * FRAME_COUNT is generated by scripts/generate-frame-manifest.mjs (predev +
 * prebuild) from the frame count of public/hero.mp4.
 *
 * It is deliberately NOT derived from the number of files in public/frames.
 * That directory still holds 219 frames left over from the abstract
 * placeholder video the first build shipped with; counting them made the
 * scrub play 141 frames of real footage and then run out into leftover
 * gradients for the remaining ~61% of the scroll — which is where the
 * philosophy, process, and closing beats all sit.
 */
const FALLBACK_BG = "#F4F1EA";
const EASE = [0.16, 1, 0.3, 1] as const;

type HeroCopy = {
  heroLabel: string;
  heroTitle: string;
  heroParagraph: string;
  heroCta: string;
  philosophyLabel: string;
  philosophyText: string;
  processLabel: string;
  processText: string;
  closingLabel: string;
  closingTitle: string;
  closingCta: string;
};

export default function ScrollHero(props: HeroCopy) {
  // Resolved on the client only — the plan depends on viewport, connection,
  // and motion preference, none of which exist during SSR. Until it resolves,
  // the markup renders the full-height scroll shell so there is no layout
  // shift when it does.
  const [plan, setPlan] = useState<FramePlan | null>(null);

  useEffect(() => {
    setPlan(planFrameLoading());
  }, []);

  if (plan?.staticOnly) {
    return <StaticHero {...props} variant={plan.variant} />;
  }

  return <ScrubHero {...props} plan={plan} />;
}

/* -------------------------------------------------------------------------
 * Reduced-motion / data-saver path
 * ---------------------------------------------------------------------- */

/**
 * One still image at normal document height — no scroll-jacking, no sequence.
 *
 * Serves three cases at once: prefers-reduced-motion (where a 500vh pinned
 * canvas is a genuine vestibular hazard), Save-Data, and 2g. All the hero's
 * copy is still shown, stacked, so nothing is lost but the animation.
 */
function StaticHero({
  variant,
  heroLabel,
  heroTitle,
  heroParagraph,
  heroCta,
  philosophyLabel,
  philosophyText,
  processLabel,
  processText,
  closingLabel,
  closingTitle,
  closingCta,
}: HeroCopy & { variant: FramePlan["variant"] }) {
  return (
    <section
      aria-label="Introduction"
      data-hero
      style={{
        position: "relative",
        minHeight: "min(88vh, 760px)",
        display: "flex",
        alignItems: "flex-end",
        background: FALLBACK_BG,
        overflow: "hidden",
      }}
    >
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={frameSrc(POSTER_FRAME_INDEX, variant)}
        alt=""
        aria-hidden="true"
        fetchPriority="high"
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          objectFit: "cover",
        }}
      />
      <div
        style={{
          position: "absolute",
          inset: 0,
          background:
            "linear-gradient(to top, rgba(32,25,18,0.78) 0%, rgba(32,25,18,0.30) 55%, rgba(32,25,18,0.12) 100%)",
        }}
      />

      <div
        style={{
          position: "relative",
          padding: "clamp(2rem, 8vh, 5rem) clamp(1.25rem, 6vw, 5rem)",
          maxWidth: 780,
        }}
      >
        <p className="hi-label" style={{ color: "#C5A45E", marginBottom: "1.1rem" }}>
          {heroLabel}
        </p>
        <h1
          style={{
            fontFamily: "var(--font-playfair)",
            fontWeight: 400,
            fontSize: "clamp(2.2rem, 5.4vw, 4.4rem)",
            color: "#F8F2E8",
            lineHeight: 1.08,
            maxWidth: "14ch",
            marginBottom: "1.4rem",
            textWrap: "balance",
          }}
        >
          {heroTitle}
        </h1>
        <p
          style={{
            fontFamily: "var(--font-inter)",
            fontWeight: 300,
            fontSize: "1.05rem",
            color: "rgba(248,242,232,0.88)",
            maxWidth: "42ch",
            marginBottom: "2rem",
          }}
        >
          {heroParagraph}
        </p>

        <div style={{ display: "flex", gap: "0.75rem", flexWrap: "wrap" }}>
          <a href="#portfolio" className="hi-cta">
            {heroCta}
          </a>
          <a
            href="#contact"
            className="hi-cta-outline"
            style={{ color: "#F8F2E8", borderColor: "rgba(248,242,232,0.4)" }}
          >
            {closingCta}
          </a>
        </div>

        {/* The two mid-scroll beats and the closing title still have to be
            readable when there is no scroll to reveal them. */}
        <dl
          style={{
            display: "grid",
            gap: "1.5rem",
            marginTop: "3rem",
            paddingTop: "2rem",
            borderTop: "1px solid rgba(248,242,232,0.22)",
          }}
        >
          {[
            { label: philosophyLabel, text: philosophyText },
            { label: processLabel, text: processText },
            { label: closingLabel, text: closingTitle },
          ].map((beat) => (
            <div key={beat.label}>
              <dt className="hi-label" style={{ color: "#C5A45E", marginBottom: "0.4rem" }}>
                {beat.label}
              </dt>
              <dd
                style={{
                  fontFamily: "var(--font-playfair)",
                  fontSize: "1.15rem",
                  lineHeight: 1.45,
                  color: "rgba(248,242,232,0.92)",
                }}
              >
                {beat.text}
              </dd>
            </div>
          ))}
        </dl>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------
 * Full scrubbing hero
 * ---------------------------------------------------------------------- */

function ScrubHero({
  plan,
  heroLabel,
  heroTitle,
  heroParagraph,
  heroCta,
  philosophyLabel,
  philosophyText,
  processLabel,
  processText,
  closingLabel,
  closingTitle,
  closingCta,
}: HeroCopy & { plan: FramePlan | null }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  // Single scroll-progress source of truth (rAF-driven, no scroll listener).
  // The canvas frame index AND every scroll-driven text transform below
  // read from this same motion value.
  const progress = useMotionValue(0);

  useEffect(() => {
    if (!plan) return;

    const canvasEl = canvasRef.current;
    const containerEl = containerRef.current;
    if (!canvasEl || !containerEl) return;
    const ctx = canvasEl.getContext("2d", { alpha: false });
    if (!ctx) return;

    const size = { cw: 0, ch: 0 };
    const images = new Array<HTMLImageElement | undefined>(FRAME_COUNT);
    const loaded = new Array<boolean>(FRAME_COUNT).fill(false);

    let currentFrame = -1;
    let rafId = 0;
    let disposed = false;
    // Set by an IntersectionObserver. When the hero is off screen the rAF loop
    // stops scheduling — previously it ran for the entire life of the page,
    // burning a frame budget on work nobody could see.
    let inView = true;

    function resizeCanvas() {
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      const cw = window.innerWidth;
      const ch = window.innerHeight;
      canvasEl!.width = Math.round(cw * dpr);
      canvasEl!.height = Math.round(ch * dpr);
      canvasEl!.style.width = `${cw}px`;
      canvasEl!.style.height = `${ch}px`;
      ctx!.setTransform(dpr, 0, 0, dpr, 0, 0);
      size.cw = cw;
      size.ch = ch;
    }

    /**
     * Nearest *loaded* frame to `wanted`.
     *
     * This is what makes strided loading work. The scroll asks for frame 137;
     * if only every 8th is in yet, this paints 136 rather than holding
     * whatever was last drawn. The result reads as a coarse scrub that
     * sharpens as the backfill lands, instead of a scrub that stutters.
     */
    function nearestLoaded(wanted: number): number {
      if (loaded[wanted]) return wanted;
      for (let offset = 1; offset < FRAME_COUNT; offset++) {
        const before = wanted - offset;
        const after = wanted + offset;
        if (before >= 0 && loaded[before]) return before;
        if (after < FRAME_COUNT && loaded[after]) return after;
      }
      return -1;
    }

    function drawFrame(index: number): boolean {
      const img = images[index];
      if (!img || !loaded[index] || !img.naturalWidth || !img.naturalHeight) {
        return false;
      }

      const scale = Math.max(size.cw / img.naturalWidth, size.ch / img.naturalHeight);
      const dw = img.naturalWidth * scale;
      const dh = img.naturalHeight * scale;
      ctx!.drawImage(img, (size.cw - dw) / 2, (size.ch - dh) / 2, dw, dh);
      return true;
    }

    resizeCanvas();
    ctx.fillStyle = FALLBACK_BG;
    ctx.fillRect(0, 0, size.cw, size.ch);

    /**
     * Fetches one frame. `decode()` before marking it loaded keeps the
     * expensive part off the paint path — drawImage on an undecoded image
     * blocks the compositor, which is exactly the jank a scrub can't afford.
     */
    function loadFrame(index: number): Promise<void> {
      if (images[index]) return Promise.resolve();

      const img = new Image();
      images[index] = img;
      img.decoding = "async";
      img.src = frameSrc(index, plan!.variant);

      return img
        .decode()
        .then(() => {
          if (disposed) return;
          loaded[index] = true;
          // First frame in: get something on screen immediately.
          if (currentFrame === -1) {
            if (drawFrame(index)) currentFrame = index;
          }
        })
        .catch(() => {
          // A single failed frame must not break the sequence; nearestLoaded
          // simply routes around it.
          images[index] = undefined;
        });
    }

    async function runLoadingPasses() {
      const first = firstPassIndices(plan!.stride);

      // Bounded concurrency. Firing every request at once starves
      // the connection and delays the frames the user is actually looking at.
      const CONCURRENCY = 6;
      async function pump(queue: number[]) {
        let cursor = 0;
        const workers = Array.from({ length: CONCURRENCY }, async () => {
          while (cursor < queue.length && !disposed) {
            const index = queue[cursor++];
            await loadFrame(index);
          }
        });
        await Promise.all(workers);
      }

      await pump(first);
      if (disposed || !plan!.backfill) return;

      // Backfill only once the browser is otherwise idle, so it never competes
      // with the rest of the page finishing its own load.
      const startBackfill = () => {
        if (!disposed) void pump(backfillIndices(plan!.stride));
      };

      if ("requestIdleCallback" in window) {
        (window as Window & typeof globalThis).requestIdleCallback(startBackfill, {
          timeout: 3000,
        });
      } else {
        setTimeout(startBackfill, 1200);
      }
    }

    void runLoadingPasses();

    function computeProgress() {
      const rect = containerEl!.getBoundingClientRect();
      const total = containerEl!.offsetHeight - window.innerHeight;
      if (total <= 0) return 0;
      return Math.max(0, Math.min(1, -rect.top / total));
    }

    function tick() {
      const p = computeProgress();
      progress.set(p);

      const wanted = Math.round(p * (FRAME_COUNT - 1));
      const paintable = nearestLoaded(wanted);

      if (paintable !== -1 && paintable !== currentFrame) {
        if (drawFrame(paintable)) currentFrame = paintable;
      }

      rafId = inView ? requestAnimationFrame(tick) : 0;
    }

    const observer = new IntersectionObserver(
      ([entry]) => {
        inView = entry.isIntersecting;
        if (inView && rafId === 0) {
          rafId = requestAnimationFrame(tick);
        } else if (!inView && rafId !== 0) {
          cancelAnimationFrame(rafId);
          rafId = 0;
        }
      },
      { threshold: 0 }
    );
    observer.observe(containerEl);

    rafId = requestAnimationFrame(tick);

    function onResize() {
      resizeCanvas();
      if (currentFrame >= 0) drawFrame(currentFrame);
    }
    window.addEventListener("resize", onResize);

    return () => {
      disposed = true;
      if (rafId) cancelAnimationFrame(rafId);
      observer.disconnect();
      window.removeEventListener("resize", onResize);
    };
  }, [plan, progress]);

  // ---- Scroll-driven overlay transforms (all derived from `progress`) ----

  const identityOpacity = useTransform(progress, [0, 0.14], [1, 0]);
  const identityY = useTransform(progress, [0, 0.14], [0, -24]);

  const rightOpacity = useTransform(progress, [0.18, 0.24, 0.5, 0.56], [0, 1, 1, 0]);
  const rightX = useTransform(progress, [0.18, 0.24, 0.5, 0.56], [40, 0, 0, 22]);
  const rightY = useTransform(progress, [0.18, 0.24, 0.5, 0.56], [0, 0, 0, -14]);

  const leftOpacity = useTransform(progress, [0.54, 0.6, 0.82, 0.88], [0, 1, 1, 0]);
  const leftX = useTransform(progress, [0.54, 0.6, 0.82, 0.88], [-40, 0, 0, -22]);
  const leftY = useTransform(progress, [0.54, 0.6, 0.82, 0.88], [0, 0, 0, -14]);

  const backdropOpacity = useTransform(progress, [0.86, 0.96], [0, 1]);
  const closingOpacity = useTransform(progress, [0.88, 0.96], [0, 1]);
  const closingY = useTransform(progress, [0.88, 0.96], [36, 0]);

  return (
    <div ref={containerRef} data-hero style={{ height: "500vh", position: "relative" }}>
      <div
        style={{
          position: "sticky",
          top: 0,
          // 100%, not 100vw: vw units include the vertical scrollbar's width,
          // which pushed the page 15px wider than the viewport and left the
          // whole site scrolling sideways.
          width: "100%",
          height: "100vh",
          overflow: "hidden",
          background: FALLBACK_BG,
        }}
      >
        <canvas
          ref={canvasRef}
          aria-hidden="true"
          style={{ display: "block", width: "100%", height: "100%" }}
        />

        {/* Overlay: never gated behind an image-loading/ready flag. Each
           text block's visibility is controlled only by its own
           scroll-progress-driven opacity below. */}
        <div style={{ position: "absolute", inset: 0, pointerEvents: "none" }}>
          {/* Warm cinematic gradient behind the initial identity text */}
          <div
            style={{
              position: "absolute",
              inset: 0,
              background:
                "linear-gradient(to top, rgba(32,25,18,0.68) 0%, rgba(32,25,18,0.20) 45%, transparent 100%)",
            }}
          />

          {/* Beat 1 — identity block */}
          <motion.div
            style={{
              opacity: identityOpacity,
              y: identityY,
              position: "absolute",
              left: 0,
              right: 0,
              bottom: 0,
              padding: "0 clamp(1.25rem, 6vw, 5rem) clamp(3rem, 8vh, 6rem)",
              maxWidth: 720,
            }}
          >
            <motion.p
              className="hi-label"
              initial={{ opacity: 0, y: 28 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1, delay: 0.05, ease: EASE }}
              style={{ color: "#C5A45E", marginBottom: "1.1rem" }}
            >
              {heroLabel}
            </motion.p>

            <motion.h1
              initial={{ opacity: 0, y: 56 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1.3, delay: 0.2, ease: EASE }}
              style={{
                fontFamily: "var(--font-playfair)",
                fontWeight: 400,
                fontSize: "clamp(2.2rem, 5.4vw, 4.4rem)",
                color: "#F8F2E8",
                lineHeight: 1.08,
                maxWidth: "14ch",
                marginBottom: "1.4rem",
                textWrap: "balance",
              }}
            >
              {heroTitle}
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 36 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1.1, delay: 0.4, ease: EASE }}
              style={{
                fontFamily: "var(--font-inter)",
                fontWeight: 300,
                fontSize: "1.05rem",
                color: "rgba(248,242,232,0.86)",
                maxWidth: "42ch",
                marginBottom: "2rem",
              }}
            >
              {heroParagraph}
            </motion.p>

            <motion.a
              href="#portfolio"
              className="hi-cta"
              initial={{ opacity: 0, y: 28 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1, delay: 0.55, ease: EASE }}
              style={{ pointerEvents: "auto" }}
            >
              {heroCta}
            </motion.a>
          </motion.div>

          {/* Beat 2 — right-side atmospheric paragraph */}
          <div
            style={{
              position: "absolute",
              top: 0,
              bottom: 0,
              right: 0,
              left: 0,
              display: "flex",
              alignItems: "center",
              justifyContent: "flex-end",
              padding: "0 clamp(1.25rem, 6vw, 5rem)",
            }}
          >
            <motion.div
              style={{
                opacity: rightOpacity,
                x: rightX,
                y: rightY,
                maxWidth: "min(380px, 100%)",
                textAlign: "right",
              }}
            >
              <p className="hi-label" style={{ color: "#C5A45E", marginBottom: "0.9rem" }}>
                {philosophyLabel}
              </p>
              <p
                style={{
                  fontFamily: "var(--font-playfair)",
                  fontWeight: 400,
                  fontSize: "clamp(1.3rem, 2.2vw, 1.7rem)",
                  color: "#F8F2E8",
                  lineHeight: 1.4,
                }}
              >
                {philosophyText}
              </p>
            </motion.div>
          </div>

          {/* Beat 3 — left-side process paragraph */}
          <div
            style={{
              position: "absolute",
              top: 0,
              bottom: 0,
              right: 0,
              left: 0,
              display: "flex",
              alignItems: "center",
              justifyContent: "flex-start",
              padding: "0 clamp(1.25rem, 6vw, 5rem)",
            }}
          >
            <motion.div
              style={{
                opacity: leftOpacity,
                x: leftX,
                y: leftY,
                maxWidth: "min(380px, 100%)",
                textAlign: "left",
              }}
            >
              <p className="hi-label" style={{ color: "#C5A45E", marginBottom: "0.9rem" }}>
                {processLabel}
              </p>
              <p
                style={{
                  fontFamily: "var(--font-playfair)",
                  fontWeight: 400,
                  fontSize: "clamp(1.3rem, 2.2vw, 1.7rem)",
                  color: "#F8F2E8",
                  lineHeight: 1.4,
                }}
              >
                {processText}
              </p>
            </motion.div>
          </div>

          {/* Beat 4 — closing center title + CTA (holds at full opacity) */}
          <motion.div
            style={{
              opacity: backdropOpacity,
              position: "absolute",
              inset: 0,
              background:
                "radial-gradient(ellipse at center, rgba(32,25,18,0.6) 0%, rgba(32,25,18,0.25) 50%, transparent 78%)",
            }}
          />
          <motion.div
            style={{
              opacity: closingOpacity,
              y: closingY,
              position: "absolute",
              inset: 0,
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              textAlign: "center",
              padding: "0 1.5rem",
            }}
          >
            <p className="hi-label" style={{ color: "#C5A45E", marginBottom: "1.2rem" }}>
              {closingLabel}
            </p>
            <h2
              style={{
                fontFamily: "var(--font-playfair)",
                fontWeight: 400,
                fontSize: "clamp(2.4rem, 6vw, 5.2rem)",
                color: "#F8F2E8",
                maxWidth: "18ch",
                lineHeight: 1.1,
                marginBottom: "2rem",
                textWrap: "balance",
              }}
            >
              {closingTitle}
            </h2>
            <motion.a
              href="#contact"
              className="hi-cta"
              whileHover={{ scale: 1.04 }}
              whileTap={{ scale: 0.98 }}
              style={{ pointerEvents: "auto" }}
            >
              {closingCta}
            </motion.a>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
